#+TITLE: Submitting job scripts on LUMI
#+AUTHOR: Anthony Scemama
#+LANGUAGE:  en
#+HTML_LINK_HOME: index.html
#+HTML_LINK_UP: index.html
#+SETUPFILE: org-html-themes/org/theme-readtheorg-local.setup

  #+begin_important
To run Quantum Package (QP) and CHAMP codes properly, some environment
variables should be set. To set up the environment, you should source
the =/project/project_465000321/environment.sh= file in your shell
when you log in:

  #+begin_src bash
source /project/project_465000321/environment.sh
  #+end_src
  #+end_important


  This file contains the following commands:

#+begin_src bash
module load cray-python
source /project/project_465000321/qp2/quantum_package.rc   # source QP environment
#+end_src

When working with SLURM, you should use =sbatch= to submit your QP and CHAMP job
scripts. For example, to submit a QP job script named =job_qp.sh=, you would use
the command:

#+begin_src bash 
sbatch job_qp.sh
#+end_src


* Example of a QP job script on LUMI

An example of a QP job script would be:

#+begin_src bash :tangle job_qp.sh
#!/bin/bash
#SBATCH --account=project_465000321
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --mem=200G
#SBATCH --partition=small

source /project/project_465000321/environment.sh

qp_srun fci COH2.ezfio > COH2.fci.out

#+end_src

  Note that QP uses shared memory parallelism with OpenMP. It will be
  efficient using all possible threads on the node.

* Example of a CHAMP job script

  For CHAMP, you should request one or many nodes with a certain number of
  processes (as there are a certain number of cores per node). There
  each MPI process uses a single thread.

An example of a CHAMP Variational Monte Carlo job script would be:

 #+begin_src bash
#!/bin/bash
#SBATCH --account=project_465000321
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=64
#SBATCH --cpus-per-task=1
#SBATCH --mem=200G
#SBATCH --partition=small

source /project/project_465000321/environment.sh

INPUT=vmc_h2o_hf.inp

OUTPUT=${INPUT%.inp}.out
srun ~filippi/champ-2.1.0/bin/vmc.mov1  -i $INPUT -o $OUTPUT -e error
 #+end_src

An example of a CHAMP Diffusion Monte Carlo job script would be:

 #+begin_src bash
#!/bin/bash
#SBATCH --account=project_465000321
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=64
#SBATCH --cpus-per-task=1
#SBATCH --mem=200G
#SBATCH --partition=small

source /project/project_465000321/environment.sh

INPUT=dmc_h2o_hf.inp

OUTPUT=${INPUT%.inp}.out
srun ~filippi/champ-2.1.0/bin/dmc.mov1  -i $INPUT -o $OUTPUT -e error
 #+end_src

